image: registry.eman.cz/docker/ruby/2.4.0:master

stages:
  - review
  - test
  - publish

rubocop:
  stage: review
  script:
    - bundle install
    - bundle exec rubocop
  only:
    - branches
  tags:
    - docker
  allow_failure: true

test:
  stage: test
  script:
    - apt update && apt install -y pdftk
    - bundle install
    - rake install:local
    - TESTOPTS="--verbose" TEST=test/*_test.rb rake test
  only:
    - branches
  tags:
    - docker
  artifacts:
    reports:
      junit: test/reports/TEST-minitest.xml

publish:
  stage: publish
  script:
    - ./script/publish.sh
    - ./script/release.sh
    - ./script/dependencies.sh
  only:
    - tags
  tags:
    - docker

